# 加解密根密码
jasypt:
  encryptor:
    password: wildcat #根密码

# redis 相关
spring:
  redis:
    password:
    host: k8s-redis-wildcat

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true

#swagger公共信息
swagger:
  title: Swagger API
  description: WildCat Spring Cloud微服务开发脚手架
  version: @project.version@
  license: Powered By WildCat
  licenseUrl: https://wildcatcloud.com/
  terms-of-service-url: https://wildcatcloud.com/
  contact:
    name: samuelQin
    email: bishengqin@gmail.com
    url: https://wildcatcloud.com
  authorization:
    name: wildcat OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://localhost:9999/auth/oauth/token


security:
  oauth2:
    client:
      # 默认放行url,如果子模块重写这里的配置就会被覆盖
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
    resource:
      loadBalanced: true
      token-info-uri: http://wildcat-auth/oauth/check_token
